#!/bin/sh

lein bin

# emacs
echo "#!/usr/bin/env sh" | cat - target/clj-plantuml > clj-plantuml && chmod +x clj-plantuml
sudo cp clj-plantuml /usr/local/bin/
# windows
cp -a target/clj-plantuml clj-plantuml.bat
